output_file: 'cv_stats.csv'

preprocess_params: 
    iet_mu:
        tanh: 
            na: ['inf']
            c: ['1', '1./obs', '2./obs', '4./obs']
        sqr:
            na: ['obs']
            c: ['1']
    iet_mu:
        tanh: 
            na: ['-inf', 'inf']
            c: ['1', '1./obs', '2./obs', '4./obs']
    uts_log:
        tanh:
            na: ['inf']
            c: [.05, .1, .5, 1.]
    iet_bur:
        sqr:
            na: [-1., 0., 1.]
            c: [.3, .5, .7]
    uts_mu:
        sqr:
            na: [0, 'uts_mu'] #TODO: deal with this/ add same value as the other 
            c: [0, .5]
    uts_sig:
        sqr:
            na: [0, .5]
            c: [0, .25]
    brtrn:
        log:
            na: [0]
            c: [1]
    wkn_t:
        log:
            na: [0]
            c: [1]
    wkl_l:
        log:
            na: [0]
            c: [1]
