output_file: 'cv_stats.csv'

n_calls: ['raw', 'rank', 'log']
overlap: ['raw', 'rank']
trains: ['raw', 'rank']
burstiness_na: ['raw', 'rank']
burstiness_km: ['raw', 'rank']
mean_iet_na: ['raw', 'rank', 'log']
mean_iet_km: ['raw', 'rank', 'log']
calltimes: ['raw']

bin_params:
    n_calls: ['log', 1.1, 30]
    trains: ['log', 1.1, 30]
    burstiness_na: ['lin', 30]
    burstiness_km: ['lin', 30]
    mean_iet_na: ['log', 1.1, 30]
    mean_iet_km: ['log', 1.1, 30]
    calltimes: ['lin', 23]
